'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Calendar, Loader2, MessageSquareText, Save, ShoppingBag } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { useFeedback } from '@/components/feedback-provider'
import type { BusinessFeature, OrderCustomerSettings } from '@/lib/types'
import { mutationErrorMessage, reportClientMutationError } from '@/lib/client-errors'
import { orderCustomerSettings } from '@/lib/order-settings'

const modules=[{key:'ordering',label:'Products & orders',icon:ShoppingBag},{key:'booking',label:'Services & booking',icon:Calendar},{key:'request_service',label:'Requests & quotes',icon:MessageSquareText}] as const

export default function BusinessModeSettings({businessId,initial}:{businessId:string;initial:BusinessFeature[]}){
  const[features,setFeatures]=useState(initial);const[busy,setBusy]=useState(false);const notify=useFeedback();const router=useRouter()
  const orderingFeature=features.find(item=>item.feature_key==='ordering');const orderConfig=orderCustomerSettings(orderingFeature?.settings)
  function update(key:typeof modules[number]['key'],changes:Partial<BusinessFeature>){setFeatures(current=>{const existing=current.find(item=>item.feature_key===key);const row:BusinessFeature=existing||{id:`draft-${key}`,business_id:businessId,feature_key:key,enabled:false,is_primary:false,display_order:modules.findIndex(item=>item.key===key),settings:{}};return [...current.filter(item=>item.feature_key!==key).map(item=>changes.is_primary?{...item,is_primary:false}:item),{...row,...changes}]})}
  function orderSetting<K extends keyof OrderCustomerSettings>(key:K,value:OrderCustomerSettings[K]){const next={...orderConfig,[key]:value,...(key==='email_required'&&value?{show_email:true}:{}),...(key==='address_required'&&value?{show_address:true}:{}),...(key==='show_email'&&!value?{email_required:false}:{}),...(key==='show_address'&&!value?{address_required:false}:{})};update('ordering',{settings:{...(orderingFeature?.settings||{}),...next}})}
  function preset(mode:'retail'|'appointment'|'service'|'hybrid'){const enabled=mode==='retail'?['ordering']:mode==='appointment'?['booking']:mode==='service'?['request_service']:modules.map(item=>item.key);const primary=mode==='retail'?'ordering':mode==='appointment'?'booking':'request_service';setFeatures(modules.map((module,index)=>{const existing=features.find(item=>item.feature_key===module.key);return {...(existing||{id:`draft-${module.key}`,business_id:businessId,feature_key:module.key,display_order:index,settings:{}}),enabled:enabled.includes(module.key),is_primary:module.key===primary}}))}
  async function save(){setBusy(true);const payload=features.filter(item=>modules.some(module=>module.key===item.feature_key)).map(({id,...item})=>id.startsWith('draft-')?item:{id,...item});const{data,error}=await createClient().from('business_features').upsert(payload,{onConflict:'business_id,feature_key'}).select();setBusy(false);if(error){reportClientMutationError('save business mode',error);notify(mutationErrorMessage('save business mode',error),'error')}else{setFeatures(data as BusinessFeature[]);notify('Business mode saved.');router.refresh()}}
  return <section className="mt-8 rounded-2xl border border-[#deded7] bg-white p-5 sm:p-6"><h2 className="font-semibold">Business mode</h2><p className="mt-1 text-xs text-[#77776f]">Start from a preset or combine features intentionally. Disabled modules disappear from the public page, dashboard, inbox, and analytics.</p><div className="mt-4 flex flex-wrap gap-2">{([['retail','Retail / product'],['appointment','Appointment'],['service','Service / quote'],['hybrid','Hybrid']] as const).map(([value,label])=><button key={value} type="button" onClick={()=>preset(value)} className="min-h-10 rounded-full border px-4 text-xs font-semibold">{label}</button>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3">{modules.map(({key,label,icon:Icon})=>{const item=features.find(feature=>feature.feature_key===key);return <article key={key} className={`rounded-xl border p-4 ${item?.enabled?'border-[#9a7048] bg-[#faf6ee]':''}`}><div className="flex items-center justify-between gap-2"><Icon size={17}/><input type="checkbox" aria-label={`Enable ${label}`} checked={item?.enabled||false} onChange={event=>update(key,{enabled:event.target.checked})}/></div><strong className="mt-3 block text-sm">{label}</strong><label className="mt-3 flex items-center gap-2 text-xs text-[#77776f]"><input type="radio" name={`owner-primary-${businessId}`} disabled={!item?.enabled} checked={item?.is_primary||false} onChange={()=>update(key,{enabled:true,is_primary:true})}/>Primary action</label></article>})}</div>{orderingFeature?.enabled&&<div className="mt-5 rounded-xl border border-[#e4e2d8] bg-[#faf9f5] p-4"><h3 className="text-sm font-semibold">Order Now customer information</h3><p className="mt-1 text-xs text-[#77776f]">Name is always required. Paid orders always require a valid email.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Fixed label="Name · required"/><Toggle label="Phone required" checked={orderConfig.phone_required} onChange={value=>orderSetting('phone_required',value)}/><Toggle label="Show email" checked={orderConfig.show_email} onChange={value=>orderSetting('show_email',value)}/><Toggle label="Email required" checked={orderConfig.email_required} onChange={value=>orderSetting('email_required',value)}/><Toggle label="Show address" checked={orderConfig.show_address} onChange={value=>orderSetting('show_address',value)}/><Toggle label="Address required" checked={orderConfig.address_required} onChange={value=>orderSetting('address_required',value)}/><Toggle label="Show notes" checked={orderConfig.show_notes} onChange={value=>orderSetting('show_notes',value)}/></div></div>}<button type="button" onClick={save} disabled={busy} className="dashboard-primary mt-4 ml-auto inline-flex items-center gap-2">{busy?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>}Save business mode</button></section>
}

function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex min-h-10 items-center gap-2 rounded-xl border bg-white px-3 text-xs font-medium"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="accent-[#1d1d1b]"/>{label}</label>}
function Fixed({label}:{label:string}){return <span className="flex min-h-10 items-center gap-2 rounded-xl border bg-white px-3 text-xs font-medium"><CheckMark/>{label}</span>}
function CheckMark(){return <span aria-hidden="true" className="grid size-4 place-items-center rounded-full bg-[#1d1d1b] text-[10px] text-white">✓</span>}
