'use client'

import { useState } from 'react'
import { Check, CircleAlert, CreditCard, ExternalLink, Loader2, ShieldCheck, Unplug } from 'lucide-react'
import { useFeedback } from '@/components/feedback-provider'
import type { BusinessPaymentSettings } from '@/lib/types'
import type { StripePlatformConfig } from '@/lib/stripe'
import ConfirmationDialog from '@/components/confirmation-dialog'

export default function PaymentsSettings({businessId,initial,platformConfig,returned}:{businessId:string;initial:BusinessPaymentSettings;platformConfig:StripePlatformConfig;returned?:string}){
  const notify=useFeedback();const[form,setForm]=useState(initial);const[busy,setBusy]=useState('');const[disconnect,setDisconnect]=useState(false)
  // Everything about "is Stripe connected / ready" in this section reflects
  // the environment this dashboard is currently running under (test or
  // live) — never the other mode's account. Order/booking payment gating
  // below stays tied to the live-mirrored legacy fields, since that's what
  // actually gates real customer checkout regardless of which mode a
  // developer happens to be viewing right now.
  const isTest=platformConfig.mode==='test'
  const accountId=isTest?form.stripe_test_account_id:form.stripe_live_account_id
  const detailsSubmitted=isTest?form.stripe_test_details_submitted:form.stripe_live_details_submitted
  const chargesEnabled=isTest?form.stripe_test_charges_enabled:form.stripe_live_charges_enabled
  const payoutsEnabled=isTest?form.stripe_test_payouts_enabled:form.stripe_live_payouts_enabled
  const connected=Boolean(accountId);const envReady=chargesEnabled&&payoutsEnabled
  const liveReady=form.stripe_charges_enabled&&form.stripe_payouts_enabled
  async function connect(){setBusy('connect');try{const r=await fetch('/api/payments/connect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({businessId})});const x=await r.json();if(!r.ok)throw new Error(x.error);window.location.assign(x.url)}catch(e){notify(e instanceof Error?e.message:'Unable to connect Stripe.','error');setBusy('')}}
  async function save(){setBusy('save');try{const r=await fetch('/api/payments/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({businessId,...form})});const x=await r.json();if(!r.ok)throw new Error(x.error);notify('Payment policies saved.')}catch(e){notify(e instanceof Error?e.message:'Unable to save settings.','error')}finally{setBusy('')}}
  async function disconnectStripe(){setBusy('disconnect');try{const r=await fetch('/api/payments/disconnect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({businessId,confirm:'DISCONNECT'})});const x=await r.json();if(!r.ok)throw new Error(x.error)
    setForm(prev=>({...prev,...(isTest
      ?{stripe_test_account_id:null,stripe_test_account_status:'disconnected',stripe_test_charges_enabled:false,stripe_test_payouts_enabled:false}
      :{stripe_live_account_id:null,stripe_live_account_status:'disconnected',stripe_live_charges_enabled:false,stripe_live_payouts_enabled:false,stripe_account_id:null,stripe_account_status:'disconnected',stripe_charges_enabled:false,stripe_payouts_enabled:false,order_payment_mode:'pay_later',booking_payment_mode:'none'})}))
    setDisconnect(false);notify(`Stripe ${isTest?'test':'live'} account disconnected from Quicklink.`)}catch(e){notify(e instanceof Error?e.message:'Unable to disconnect Stripe.','error')}finally{setBusy('')}}
  return <div className="mt-8 grid gap-6"><section className="rounded-2xl border border-[#deded7] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#1d1d1b] text-[#d19a6a]"><CreditCard size={20}/></span><div><h2 className="font-semibold">Stripe payments</h2><p className="mt-1 text-xs text-[#77776f]">Each business is its own merchant. Stripe handles identity, bank details, cards and payouts.</p></div></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${envReady?'bg-emerald-50 text-emerald-700':connected?'bg-amber-50 text-amber-800':'bg-[#f0eee7] text-[#77776f]'}`}>{envReady?'Enabled':connected?'Action needed':'Not connected'}</span></div>
    {returned==='returned'&&<p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Stripe returned you to Quicklink. The current capability status is shown below.</p>}{returned==='sync-error'&&<p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">We could not refresh the Stripe status. Try opening onboarding again.</p>}{returned==='stale'&&<p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">The saved Stripe account no longer exists or belongs to a different Stripe mode. Choose Continue Stripe setup and Quicklink will repair it.</p>}{returned==='live-localhost-blocked'&&<p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">Live Stripe Connect onboarding requires HTTPS. Use the deployed Quicklink site or switch to Stripe test mode locally.</p>}
    <div className="mt-5 grid gap-2 sm:grid-cols-2"><Status ok={platformConfig.paymentsReady} label={`Quicklink platform: ${platformConfig.mode} mode`}/><Status ok={connected} label={`Business Stripe: ${connected?`${platformConfig.mode} account connected`:'not connected'}`}/><Status ok={detailsSubmitted} label="Business details submitted"/><Status ok={chargesEnabled} label="Business payments enabled"/><Status ok={payoutsEnabled} label="Business payouts enabled"/></div>
    {!platformConfig.connectReady&&<p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><strong>Quicklink Stripe setup is incomplete.</strong> Add a valid <code>STRIPE_SECRET_KEY</code> on the server before connecting this business.</p>}
    {platformConfig.connectReady&&!platformConfig.paymentsReady&&<p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">Stripe onboarding is available, but live payment handling is incomplete. Configure: <code>{platformConfig.missing.join(', ')}</code>.</p>}
    {platformConfig.paymentsReady&&!connected&&<p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><strong>Stripe is ready. Connect this business to start accepting payments.</strong> Stripe’s hosted onboarding will collect the business and payout details.</p>}
    <div className="mt-5 flex flex-wrap gap-2">{!envReady?<button disabled={Boolean(busy)||!platformConfig.connectReady} onClick={connect} title={!platformConfig.connectReady?'Configure STRIPE_SECRET_KEY on the server first.':undefined} className="dashboard-primary inline-flex items-center gap-2 disabled:cursor-not-allowed disabled:opacity-50">{busy==='connect'?<Loader2 size={15} className="animate-spin"/>:<ShieldCheck size={15}/>} {connected?'Continue Stripe setup':'Connect Stripe'}</button>:<a href="https://dashboard.stripe.com" target="_blank" rel="noreferrer" className="dashboard-primary inline-flex items-center gap-2">Open Stripe <ExternalLink size={14}/></a>}{connected&&<button onClick={()=>setDisconnect(true)} className="dashboard-secondary inline-flex items-center gap-2 text-red-700"><Unplug size={14}/>Disconnect</button>}</div>
  </section>
  <section className="rounded-2xl border border-[#deded7] bg-white p-5 sm:p-6"><h2 className="font-semibold">Order payments</h2><p className="mt-1 text-xs text-[#77776f]">Choose whether product orders must be paid online before they enter your active inbox.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Choice active={form.order_payment_mode==='online_required'} title="Pay online" body="Stripe confirms payment before the order becomes New." onClick={()=>setForm({...form,order_payment_mode:'online_required'})}/><Choice active={form.order_payment_mode==='pay_later'} title="Pay later" body="Accept an order without collecting online payment." onClick={()=>setForm({...form,order_payment_mode:'pay_later'})}/></div>{form.order_payment_mode==='online_required'&&!liveReady&&<p className="mt-3 flex items-center gap-2 text-xs text-amber-800"><CircleAlert size={14}/>Ordering stays unavailable until your live Stripe account enables payments and payouts.</p>}</section>
  <section className="rounded-2xl border border-[#deded7] bg-white p-5 sm:p-6"><h2 className="font-semibold">Booking payments</h2><p className="mt-1 text-xs text-[#77776f]">Choose how customers pay for appointments. The public booking page follows whatever you pick here.</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{([['full','Pay in full','Confirm only after full payment.',true],['deposit','Require deposit','Collect part now and show the remainder clearly.',true],['none','Pay at appointment','Book now and collect payment when the customer arrives.',false]] as const).map(([value,label,body,needsStripe])=><Choice key={value} active={form.booking_payment_mode===value} title={label} body={body} disabled={needsStripe&&!liveReady} disabledHint="Connect Stripe and finish onboarding before enabling this." onClick={()=>setForm({...form,booking_payment_mode:value})}/>)}</div>{(form.booking_payment_mode==='full'||form.booking_payment_mode==='deposit')&&!liveReady&&<p className="mt-3 flex items-center gap-2 text-xs text-amber-800"><CircleAlert size={14}/>This mode can&apos;t actually collect payment yet — connect Stripe and finish onboarding, or bookings will confirm without charging.</p>}{form.booking_payment_mode==='deposit'&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-semibold">Deposit type<select className="form-control" value={form.deposit_type} onChange={e=>setForm({...form,deposit_type:e.target.value as 'percent'|'fixed'})}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label className="grid gap-1.5 text-xs font-semibold">{form.deposit_type==='percent'?'Percent':'Amount'}<input className="form-control" type="number" min="0" step={form.deposit_type==='percent'?1:0.01} max={form.deposit_type==='percent'?100:1000000} value={form.deposit_type==='percent'?form.deposit_value:(form.deposit_value/100).toFixed(2)} onChange={e=>setForm({...form,deposit_value:form.deposit_type==='percent'?Number(e.target.value):Math.round(Number(e.target.value)*100)})}/></label></div>}<label className="mt-5 flex items-center justify-between gap-4 rounded-xl border p-4"><span><strong className="block text-sm">Allow multiple services per booking</strong><small className="text-[#77776f]">Combined price and duration determine payment and availability.</small></span><input type="checkbox" checked={form.allow_multiple_services} onChange={e=>setForm({...form,allow_multiple_services:e.target.checked})} className="size-5 accent-[#1d1d1b]"/></label></section>
  <section className="rounded-2xl border border-[#deded7] bg-white p-5 sm:p-6"><h2 className="font-semibold">Cancellation &amp; refund policy</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-semibold">Booking refund policy<select className="form-control" value={form.booking_refund_policy} onChange={e=>setForm({...form,booking_refund_policy:e.target.value as BusinessPaymentSettings['booking_refund_policy']})}><option value="window">Refundable until a cutoff</option><option value="non_refundable">Non-refundable</option><option value="manual">Manual approval</option></select></label><label className="grid gap-1.5 text-xs font-semibold">Cancellation cutoff (hours)<input className="form-control" type="number" min="0" max="8760" value={form.cancellation_window_hours} onChange={e=>setForm({...form,cancellation_window_hours:Number(e.target.value)})}/></label><label className="grid gap-1.5 text-xs font-semibold">Deposit refunds<select className="form-control" value={form.deposit_refund_policy} onChange={e=>setForm({...form,deposit_refund_policy:e.target.value as BusinessPaymentSettings['deposit_refund_policy']})}><option value="follow_window">Follow booking window</option><option value="refundable">Refundable</option><option value="non_refundable">Non-refundable</option></select></label><label className="grid gap-1.5 text-xs font-semibold">Customer order cancellation<select className="form-control" value={form.order_cancellation_policy} onChange={e=>setForm({...form,order_cancellation_policy:e.target.value as BusinessPaymentSettings['order_cancellation_policy']})}><option value="new_only">New only</option><option value="new_confirmed">New + Confirmed</option><option value="never">Never automatically</option></select></label></div></section>
  <button disabled={Boolean(busy)} onClick={save} className="dashboard-primary ml-auto inline-flex items-center gap-2">{busy==='save'?<Loader2 size={15} className="animate-spin"/>:<Check size={15}/>}Save payment policies</button>
  <ConfirmationDialog open={disconnect} title={`Disconnect ${isTest?'test':'live'} Stripe?`} body={`Quicklink will stop creating ${isTest?'test-mode':'online'} payments${isTest?' locally':''}. Your Stripe account and its records remain in Stripe. Pending payments or refunds must finish first.`} confirmLabel="Disconnect" busy={busy==='disconnect'} onCancel={()=>setDisconnect(false)} onConfirm={disconnectStripe}/>
  </div>
}
function Status({ok,label}:{ok:boolean;label:string}){return <div className="flex items-center gap-2 rounded-xl bg-[#fafaf7] px-3 py-2 text-sm"><span className={`grid size-5 place-items-center rounded-full ${ok?'bg-emerald-100 text-emerald-700':'bg-[#e9e6df] text-[#8d8b84]'}`}>{ok?<Check size={12}/>:<span className="size-1.5 rounded-full bg-current"/>}</span>{label}</div>}
function Choice({active,title,body,onClick,disabled,disabledHint}:{active:boolean;title:string;body:string;onClick:()=>void;disabled?:boolean;disabledHint?:string}){return <button type="button" disabled={disabled} title={disabled?disabledHint:undefined} onClick={onClick} className={`rounded-xl border p-4 text-left disabled:cursor-not-allowed disabled:opacity-50 ${active?'border-[#8b6b3d] bg-[#faf6ee]':'border-[#e4e2d8]'}`}><strong className="text-sm">{title}</strong><span className="mt-1 block text-xs leading-5 text-[#77776f]">{body}</span></button>}
