import Link from 'next/link'
import QuicklinkLogo from '@/components/quicklink-logo'

export const metadata = { title: 'Terms of Service | Quicklink', description: 'Terms for businesses and visitors using Quicklink.' }

export default function TermsPage() {
  return <main className="min-h-screen bg-[#f6f4ef] px-5 py-8 text-[#1d1d1b] sm:py-12"><div className="mx-auto max-w-3xl"><Link href="/" className="inline-flex"><QuicklinkLogo/></Link><div className="mt-12 border-b border-[#d8d3c9] pb-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#a3643c]">Quicklink legal</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Terms of Service</h1><p className="mt-3 text-sm text-[#77736c]">Last updated September 13, 2026</p></div><article className="grid gap-9 py-10 text-[15px] leading-7 text-[#57544e]">
    <Section title="The service"><p>Quicklink provides QR-linked business pages, customer-action modules, activity management, and optional integrations. Features may change as the service develops.</p></Section>
    <Section title="Business responsibilities"><p>Businesses are responsible for the accuracy, legality, availability, pricing, descriptions, images, links, services, products, and offers they publish. Quicklink does not provide or guarantee the underlying business services and is not a party to transactions between a business and its customers.</p></Section>
    <Section title="Customer information"><p>Customers must provide accurate information when submitting orders, bookings, or service requests. Businesses are responsible for using submitted information appropriately and following laws that apply to their own operations.</p></Section>
    <Section title="Access and security"><p>Administrators and businesses must protect their credentials and private Activity links. A private link can grant access without a password; promptly regenerate it if it may have been exposed. Do not use Quicklink to access another business’s information or interfere with the service.</p></Section>
    <Section title="Third-party integrations"><p>Supabase, hosting services, browser push services, email providers, and Google Calendar operate under their own terms and availability. Google Calendar connection is optional and may be disconnected. Quicklink is not responsible for third-party outages, account restrictions, or changes.</p></Section>
    <Section title="Availability and acceptable use"><p>Quicklink is provided on an as-available basis. Continuous operation, delivery of notifications, and uninterrupted access are not guaranteed. You may not use the service for unlawful, fraudulent, abusive, deceptive, infringing, or security-disrupting activity.</p></Section>
    <Section title="Liability"><p>To the extent permitted by law, Quicklink is not liable for indirect, incidental, special, or consequential losses, lost revenue, missed appointments, failed notifications, third-party failures, or business-customer disputes. Nothing here excludes liability that cannot legally be excluded.</p></Section>
    <Section title="Changes and termination"><p>Quicklink may modify, suspend, or end features or access when reasonably necessary, including for misuse, security, maintenance, or service changes. These terms may be updated, with the current version posted here.</p></Section>
    <Section title="Contact"><p>Questions about these terms can be sent through the call, text, or email option in the <Link href="/#contact" className="underline decoration-[#b36b3e] underline-offset-4">Quicklink contact section</Link>.</p></Section>
  </article><footer className="flex flex-wrap gap-5 border-t border-[#d8d3c9] py-7 text-sm"><Link href="/">Home</Link><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link></footer></div></main>
}
function Section({title,children}:{title:string;children:React.ReactNode}) { return <section><h2 className="mb-2 text-lg font-semibold text-[#1d1d1b]">{title}</h2>{children}</section> }
