import Link from 'next/link'
import QuicklinkLogo from '@/components/quicklink-logo'

export const metadata = { title: 'Privacy Policy | Quicklink', description: 'How Quicklink collects, uses and protects business and customer information.' }

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" updated="September 13, 2026">
    <Section title="What Quicklink is"><p>Quicklink provides branded public pages and QR-code destinations for local businesses. Depending on what a business enables, customers can follow links, place orders, request services, or book appointments.</p></Section>
    <Section title="Information we handle"><p>Customers may submit a name, phone number, order or booking details, service requests, preferred dates, addresses, and optional notes. Businesses configure their public profile, links, services, products, hours, images, notification preferences, and integration settings.</p></Section>
    <Section title="Storage and service providers"><p>Quicklink uses Supabase to store business configuration and customer activity. Hosting, email delivery, browser push services, and other infrastructure providers process limited information as needed to operate their respective features. Quicklink does not claim that any internet service is completely secure or continuously available.</p></Section>
    <Section title="Notifications"><p>Businesses may optionally enable browser push notifications on individual devices. Push subscriptions contain technical browser/device routing information. Businesses may also optionally configure email notifications. Customer email is not required for the current booking flow.</p></Section>
    <Section title="Google Calendar"><p>Connecting Google Calendar is optional. When connected, Quicklink accesses calendar event and free/busy information only to check available times, create booking events, update booking events, and cancel or remove booking events. Quicklink does not sell Google Calendar data. A business can disconnect Google Calendar from its Quicklink editor, which removes the stored connection from Quicklink; it may also revoke access from its Google Account settings.</p></Section>
    <Section title="Access, retention, and security"><p>Business activity is available to the Quicklink administrator and, when enabled, through a business-specific private Activity link. Anyone with that private link may be able to view or manage the activity it exposes, so businesses must protect it and request regeneration if it is shared improperly. Records may be archived instead of immediately deleted. We use access controls and server-side credentials, but no system can guarantee absolute security.</p></Section>
    <Section title="Questions"><p>For privacy questions or requests, use the call, text, or email option available in the <Link href="/#contact" className="underline decoration-[#b36b3e] underline-offset-4">Quicklink contact section</Link>.</p></Section>
  </LegalPage>
}

function LegalPage({title,updated,children}:{title:string;updated:string;children:React.ReactNode}) { return <main className="min-h-screen bg-[#f6f4ef] px-5 py-8 text-[#1d1d1b] sm:py-12"><div className="mx-auto max-w-3xl"><Link href="/" className="inline-flex"><QuicklinkLogo/></Link><div className="mt-12 border-b border-[#d8d3c9] pb-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#a3643c]">Quicklink legal</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{title}</h1><p className="mt-3 text-sm text-[#77736c]">Last updated {updated}</p></div><article className="grid gap-9 py-10 text-[15px] leading-7 text-[#57544e]">{children}</article><footer className="flex flex-wrap gap-5 border-t border-[#d8d3c9] py-7 text-sm"><Link href="/">Home</Link><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link></footer></div></main> }
function Section({title,children}:{title:string;children:React.ReactNode}) { return <section><h2 className="mb-2 text-lg font-semibold text-[#1d1d1b]">{title}</h2>{children}</section> }
