import type { Metadata } from 'next'
import { createClient } from '@/lib/supabase/server'
import { requireOwnerContext } from '@/lib/dashboard/business-context'
import NotificationIntegrationsSettings from '@/components/dashboard/notification-integrations-settings'
import BusinessHoursSettings from '@/components/dashboard/business-hours-settings'
import BookingAvailabilitySettings from '@/components/dashboard/booking-availability-settings'
import type { BookingSettings, BusinessHour, NotificationSettings } from '@/lib/types'
export const metadata:Metadata={title:'Notifications & Integrations — Quicklink',robots:{index:false,follow:false}}
export default async function IntegrationsPage({searchParams}:{searchParams:Promise<{business?:string}>}){const{business:preferred}=await searchParams;const{business}=await requireOwnerContext(preferred);const supabase=await createClient();const[{data},{data:hours},{data:bookingFeature},{data:calendarConnection}]=await Promise.all([supabase.from('business_notification_settings').select('*').eq('business_id',business.id).maybeSingle(),supabase.from('business_hours').select('*').eq('business_id',business.id).order('day_of_week'),supabase.from('business_features').select('*').eq('business_id',business.id).eq('feature_key','booking').maybeSingle(),supabase.from('business_calendar_connections').select('business_id').eq('business_id',business.id).maybeSingle()]);const initial=(data||{business_id:business.id,notification_phone:business.phone,order_sms:false,booking_sms:false,quote_sms:false,delivery_sms:false,notification_email:business.email,push_notifications_enabled:true,email_notifications_enabled:false,calendar_integration_enabled:false}) as NotificationSettings;const bookingDefaults:BookingSettings={button_title:'Book Now',buffer_minutes:0,minimum_notice_minutes:60,sms_enabled:false,slot_interval_minutes:15};const bookingSettings={...bookingDefaults,...(bookingFeature?.settings||{})} as BookingSettings;const hasBookableHours=(hours||[]).some((hour)=>!hour.closed&&hour.open_time&&hour.close_time);return <main className="px-5 py-8 lg:px-10 lg:py-10"><div className="mx-auto max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#8b6b3d]">{business.name}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Operations &amp; integrations</h1><p className="mt-2 text-[#77776f]">Manage business hours, notification delivery, and Google Calendar booking availability.</p><div className="mt-8 grid gap-6"><BusinessHoursSettings businessId={business.id} initial={(hours||[]) as BusinessHour[]}/><BookingAvailabilitySettings businessId={business.id} featureRowId={bookingFeature?.id??null} initial={bookingSettings} enabled={bookingFeature?.enabled??false} isPrimary={bookingFeature?.is_primary??false} displayOrder={bookingFeature?.display_order??0} hasBookableHours={hasBookableHours} calendarConnected={Boolean(calendarConnection)}/><NotificationIntegrationsSettings businessId={business.id} initial={initial}/></div></div></main>}
