'use client'

import { useState } from 'react'
import { ArrowUpRight, BarChart3, Camera, Check, CirclePlay, ExternalLink, MapPin, Menu, MessageSquare, Phone, QrCode, ScanLine, ShieldCheck, Sparkles, Star, Store, Zap } from 'lucide-react'
import Link from 'next/link'
import QuicklinkLogo from '@/components/quicklink-logo'
import HomeInteractive from '@/components/home-interactive'

const links = [
  ['Google reviews', Star], ['Booking', Store], ['Instagram', Camera], ['Call business', Phone], ['Directions', MapPin], ['QR code', QrCode], ['Live analytics', BarChart3], ['Smart updates', Zap],
] as const

const defaultContactPhone = '+18453901785'

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const contactPhone = process.env.NEXT_PUBLIC_CONTACT_PHONE?.trim() || defaultContactPhone
  const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL?.trim()
  const phoneHref = contactPhone ? `tel:${contactPhone.replace(/[^+\d]/g, '')}` : undefined
  const smsHref = contactPhone ? `sms:${contactPhone.replace(/[^+\d]/g, '')}?body=${encodeURIComponent("Hi! I'm interested in a Quicklink page for my business.")}` : undefined

  return <main className="min-h-screen overflow-x-clip bg-[#f5f4ef] text-[#171715]">
    <nav className="relative z-30 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
      <Link href="/"><QuicklinkLogo className="text-lg"/></Link>
      <div className="hidden items-center gap-9 text-sm text-[#77766e] md:flex"><a href="#how">How it works</a><a href="#features">Features</a><a href="#examples">Examples</a></div>
      <div className="flex items-center gap-3"><a href="#contact" className="rounded-full bg-[#171715] px-5 py-2.5 text-sm font-medium text-white transition hover:-translate-y-0.5 hover:bg-[#302f2a]">Get started <ArrowUpRight className="ml-1 inline" size={15}/></a><button onClick={() => setMenuOpen(!menuOpen)} className="md:hidden" aria-label="Open menu" aria-expanded={menuOpen}><Menu size={20}/></button></div>
      {menuOpen && <div className="absolute right-6 top-20 grid gap-4 rounded-2xl border border-[#deddd5] bg-white p-5 text-sm shadow-xl md:hidden"><a href="#how">How it works</a><a href="#features">Features</a><a href="#examples">Examples</a></div>}
    </nav>

    <section className="relative mx-auto grid max-w-7xl gap-16 px-6 pb-24 pt-12 lg:grid-cols-[0.92fr_1.08fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-20">
      <div className="relative z-10"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#deddd5] bg-white/60 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#8e603d]"><span className="flex size-5 items-center justify-center rounded-full bg-[#e8cdb7]"><Sparkles size={11}/></span> The post-scan experience</div><h1 className="max-w-2xl text-balance text-[4.6rem] font-semibold leading-[0.88] tracking-[-0.075em] sm:text-[6.4rem]">Make the<br/><span className="relative inline-block text-[#b36b3e]">next click</span><br/>count<span className="text-[#171715]">.</span></h1><p className="mt-8 max-w-lg text-lg leading-8 text-[#6e6d66]">One beautiful QR page that turns curious customers into reviews, bookings, followers, and regulars.</p><div className="mt-9 flex flex-wrap items-center gap-4"><a href="#contact" className="inline-flex items-center gap-2 rounded-full bg-[#171715] px-6 py-3.5 text-sm font-semibold text-white shadow-[0_12px_30px_rgba(23,23,21,0.14)] transition hover:-translate-y-1">Build your page <ArrowUpRight size={16}/></a><a href="#demo" className="inline-flex items-center gap-2 rounded-full border border-[#d3d1c8] bg-white/45 px-6 py-3.5 text-sm font-semibold"><CirclePlay size={16}/> See the magic</a></div><div className="mt-8 flex items-center gap-6 text-xs text-[#8d8b82]"><span className="flex items-center gap-2"><Check size={14} className="text-[#b36b3e]"/> No app download</span><span className="flex items-center gap-2"><Check size={14} className="text-[#b36b3e]"/> Update once, forever</span></div></div>
      <div id="hero-preview" className="relative mx-auto w-full max-w-[30rem] lg:mr-0"><div className="absolute -right-8 top-8 hidden h-44 w-44 rounded-full border border-dashed border-[#cfc2b5] lg:block"/><div className="absolute -left-6 bottom-8 hidden h-20 w-20 rounded-full bg-[#e8cdb7]/70 lg:block"/><div className="relative grid min-h-[560px] place-items-center rounded-[2.5rem] border border-[#ded9cf] bg-[#e9e3d9] p-8 shadow-[0_24px_80px_rgba(69,55,39,0.12)]"><div className="absolute left-6 top-6 flex items-center gap-2 rounded-full bg-white/70 px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#8a6a55]"><ScanLine size={13}/> Live preview</div><div className="phone-float relative w-full max-w-[270px] overflow-hidden rounded-[2.3rem] border-[7px] border-[#282825] bg-[#efe9df] shadow-2xl"><div className="flex items-center justify-between bg-[#282825] px-5 py-2 text-[9px] text-white"><span>9:41</span><span>● ● ●</span></div><div className="px-6 pb-8 pt-7 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-[1.2rem] bg-[#c9a77a] text-xl font-semibold text-white">FC</div><h2 className="mt-4 text-2xl font-semibold tracking-tight">Fresh Cuts</h2><p className="mt-1 text-xs text-[#77736c]">Classic cuts. Modern craft.</p><div className="mt-6 grid gap-2.5"><div className="flex items-center gap-2 rounded-xl bg-[#171715] px-3 py-3.5 text-left text-[11px] font-medium text-white"><Star size={14} fill="currentColor"/> Leave a review <ExternalLink className="ml-auto" size={12}/></div>{['Book an appointment','Follow on Instagram','Get directions'].map((x, i) => <div key={x} className="flex items-center gap-2 rounded-xl bg-white/75 px-3 py-3.5 text-left text-[11px] font-medium"><span className="text-[#8e603d]">{i === 0 ? '◷' : i === 1 ? '◎' : '⌖'}</span>{x}<ExternalLink className="ml-auto" size={12}/></div>)}</div><div className="mt-6 flex items-center justify-center gap-1.5 text-[9px] text-[#99938a]"><QrCode size={11}/> powered by Quicklink</div></div></div><div className="absolute bottom-7 right-7 flex items-center gap-2 rounded-2xl border border-[#d4c7bb] bg-white/80 px-3 py-2.5 text-xs font-medium text-[#6f5849] shadow-lg"><ShieldCheck size={15}/> Works offline-ready</div></div></div>
    </section>

    <section className="border-y border-[#e1e0d8] bg-[#171715] px-6 py-5 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-10 gap-y-3 text-center text-xs font-medium tracking-wide text-[#b7b5ac] sm:justify-between"><span className="text-[#f5f4ef]">Built for the businesses people remember.</span><span>Barbershops</span><span>Salons</span><span>Restaurants</span><span>Auto shops</span><span>Studios</span></div></section>

    <HomeInteractive/>

    <section id="how" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-14 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#b36b3e]">Not another link list</p><h2 className="mt-4 max-w-md text-4xl font-semibold leading-tight tracking-[-0.05em] sm:text-5xl">The tiny page that does a lot.</h2><p className="mt-5 max-w-sm leading-7 text-[#77766e]">The best QR experiences feel instant. No hunting. No friction. Just the right action at the right moment.</p></div><div className="grid gap-4 sm:grid-cols-3"><div className="step-card"><span className="step-number">01</span><div className="mt-12 text-3xl">✦</div><h3 className="mt-5 text-lg font-semibold">Shape the moment</h3><p className="mt-2 text-sm leading-6 text-[#77766e]">We turn your brand and best links into one focused destination.</p></div><div className="step-card"><span className="step-number">02</span><div className="mt-12 text-3xl">⌁</div><h3 className="mt-5 text-lg font-semibold">Place the signal</h3><p className="mt-2 text-sm leading-6 text-[#77766e]">Your QR lives on the counter, receipt, window, or anywhere attention lands.</p></div><div className="step-card"><span className="step-number">03</span><div className="mt-12 text-3xl">↗</div><h3 className="mt-5 text-lg font-semibold">Watch it work</h3><p className="mt-2 text-sm leading-6 text-[#77766e]">See what customers tap, then improve the experience without reprinting.</p></div></div></div></section>

    <section id="features" className="bg-white px-6 py-24 lg:px-10"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#b36b3e]">Small link. Big lift.</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">Everything customers need.<br/><span className="text-[#b36b3e]">Nothing they don&apos;t.</span></h2><p className="mt-6 max-w-md leading-7 text-[#77766e]">Every button is designed for a thumb, every page is tuned for speed, and every change goes live instantly.</p><div className="mt-8 flex items-center gap-3 text-sm font-medium"><span className="flex size-10 items-center justify-center rounded-full bg-[#e8cdb7] text-[#8e603d]"><BarChart3 size={18}/></span> See which action drives business</div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{links.map(([label, Icon], i) => <div key={label} className={`feature-tile ${i === 0 ? 'bg-[#171715] text-white' : ''}`}><Icon size={20} className={i === 0 ? 'text-[#e8cdb7]' : 'text-[#b36b3e]'}/><span>{label}</span></div>)}</div></div></section>


    <section id="contact" className="relative overflow-hidden bg-[#171715] px-6 py-28 text-center text-white lg:px-10"><div className="absolute left-1/2 top-1/2 size-[34rem] -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/10"/><div className="relative mx-auto max-w-3xl"><div className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-[#e8cdb7] text-[#171715]"><Zap size={24} fill="currentColor"/></div><h2 className="mx-auto mt-7 max-w-2xl text-5xl font-semibold tracking-[-0.06em] sm:text-7xl">Let&apos;s build your<br/><span className="text-[#e8cdb7]">Quicklink.</span></h2><p className="mx-auto mt-6 max-w-md leading-7 text-[#aaa89f]">Call or text for a fast, no-pressure conversation about what your business needs.</p>{contactPhone ? <div className="mt-9 flex flex-wrap justify-center gap-3"><a href={phoneHref} className="inline-flex items-center gap-2 rounded-full bg-[#f5f4ef] px-7 py-4 text-sm font-semibold text-[#171715] transition hover:-translate-y-1"><Phone size={16}/> Call us</a><a href={smsHref} className="inline-flex items-center gap-2 rounded-full border border-white/20 px-7 py-4 text-sm font-semibold text-white transition hover:-translate-y-1 hover:bg-white/10"><MessageSquare size={16}/> Text us</a></div> : contactEmail ? <a href={`mailto:${contactEmail}?subject=${encodeURIComponent('Quicklink for my business')}`} className="mt-9 inline-flex items-center gap-2 rounded-full bg-[#f5f4ef] px-7 py-4 text-sm font-semibold text-[#171715] transition hover:-translate-y-1">Send us an email <ArrowUpRight size={16}/></a> : <p className="mx-auto mt-8 max-w-md rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-sm text-[#c9c6bc]">Contact details are being added. Please check back soon.</p>}</div></section>
    <footer className="border-t border-white/10 bg-[#171715] px-6 py-8 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 text-sm text-[#77766e]"><QuicklinkLogo className="text-[#f5f4ef]" markClassName="border border-white/10 bg-white/5"/><span>QR pages for local business.</span><span>© 2026 Quicklink</span></div></footer>
  </main>
}
