'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { CalendarDays, CheckCircle2, ExternalLink, XCircle } from 'lucide-react'
import StatusTimeline from '@/components/status-timeline'
import ConfirmationDialog from '@/components/confirmation-dialog'

type ManagedBooking = { customerName:string;businessName:string;businessSlug:string;serviceName:string|null;services:Array<{service_name:string;price_cents:number;duration_minutes:number}>;date:string;startTime:string;endTime:string;status:string;totalPriceCents:number;amountDueCents:number;amountPaidCents:number;paymentStatus:string;currency:string;policySnapshot:Record<string,unknown>;receiptUrl:string|null }

export default function BookingManageCard({ token, booking }: { token: string; booking: ManagedBooking }) {
  const router=useRouter()
  const [status,setStatus]=useState(booking.status);const[paymentStatus,setPaymentStatus]=useState(booking.paymentStatus);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[modal,setModal]=useState(false)
  async function cancel(){setBusy(true);setError('');const response=await fetch('/api/booking/manage/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,confirm:'CANCEL'})});const result=await response.json();setBusy(false);if(!response.ok){setError(result.error||'Unable to cancel this appointment.');setModal(false)}else{setStatus('cancelled');if(result.refund)setPaymentStatus(result.refund.status==='succeeded'?'refunded':'refund_pending');setModal(false)}}
  const date=new Date(`${booking.date}T00:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})
  const manual=Boolean(booking.amountPaidCents&&booking.policySnapshot.booking_refund_policy==='manual')
  const cancellable=!['cancelled','completed','no_show'].includes(status)&&!manual
  useEffect(()=>{setStatus(booking.status);setPaymentStatus(booking.paymentStatus)},[booking.status,booking.paymentStatus])
  useEffect(()=>{if(status!=='pending_payment'&&paymentStatus!=='pending')return;let tries=0;const timer=window.setInterval(()=>{tries+=1;router.refresh();if(tries>=15)window.clearInterval(timer)},2000);return()=>window.clearInterval(timer)},[status,paymentStatus,router])
  return <main className="min-h-screen bg-[#f6f3ed] px-4 py-10 text-[#1d1d1b]"><section className="mx-auto max-w-xl overflow-hidden rounded-3xl border border-[#ded8cc] bg-white shadow-[0_24px_70px_rgba(38,28,17,.12)]"><div className="bg-[#1d1d1b] px-6 py-7 text-white"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#d19a6a]">Quicklink appointment</p><h1 className="mt-2 text-2xl font-semibold">Manage your booking</h1></div><div className="p-6 sm:p-8">
    {status==='pending_payment'&&<p className="mb-5 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">Your time is held while payment processes. The booking confirms only after Stripe reports success.</p>}
    <div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-2xl bg-[#f2e8db] text-[#9a6339]"><CalendarDays size={22}/></span><div><h2 className="text-xl font-semibold">{booking.businessName}</h2><p className="mt-1 text-sm text-[#77776f]">For {booking.customerName}</p></div></div>
    <StatusTimeline status={status} steps={status==='pending_payment'?[{value:'pending_payment',label:'Payment pending'}]:[{value:'pending',label:'Booked'},{value:'confirmed',label:'Confirmed'},{value:'completed',label:'Completed'}]}/>
    <section className="mt-7 rounded-2xl bg-[#faf8f3] p-5"><h3 className="text-xs font-semibold uppercase tracking-[.1em] text-[#77776f]">Appointment</h3><dl className="mt-3 grid gap-2 text-sm"><Row label="Date" value={date}/><Row label="Time" value={`${formatTime(booking.startTime)}–${formatTime(booking.endTime)}`}/><Row label="Status" value={status.replaceAll('_',' ')}/></dl></section>
    <section className="mt-5"><h3 className="text-xs font-semibold uppercase tracking-[.1em] text-[#77776f]">Services</h3><div className="mt-3 divide-y rounded-2xl border px-4">{(booking.services.length?booking.services:[{service_name:booking.serviceName||'Appointment',price_cents:booking.totalPriceCents,duration_minutes:0}]).map((service,index)=><div key={`${service.service_name}-${index}`} className="flex justify-between gap-3 py-3 text-sm"><span>{service.service_name}{service.duration_minutes?` · ${service.duration_minutes} min`:''}</span><strong>{money(service.price_cents,booking.currency)}</strong></div>)}<div className="flex justify-between py-4"><strong>Total</strong><strong>{money(booking.totalPriceCents,booking.currency)}</strong></div></div></section>
    <section className="mt-5 rounded-2xl bg-[#faf8f3] p-5"><h3 className="text-xs font-semibold uppercase tracking-[.1em] text-[#77776f]">Payment</h3><dl className="mt-3 grid gap-2 text-sm"><Row label="Status" value={paymentStatus.replaceAll('_',' ')}/><Row label="Paid today" value={money(booking.amountPaidCents,booking.currency)}/>{booking.totalPriceCents>booking.amountPaidCents&&<Row label="Remaining at appointment" value={money(booking.totalPriceCents-booking.amountPaidCents,booking.currency)}/>}</dl>{booking.receiptUrl&&<a href={booking.receiptUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-[#8b6b3d]">View payment receipt <ExternalLink size={13}/></a>}</section>
    {error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    {status==='cancelled'?<div className="mt-6 flex items-center gap-2 rounded-xl bg-[#faf8f3] px-4 py-3 text-sm font-medium"><CheckCircle2 size={18} className="text-[#9a6339]"/>This appointment has been cancelled{paymentStatus==='refunded'?' and refunded.':paymentStatus==='refund_pending'?' and the refund is processing.':'.'}</div>:cancellable?<button onClick={()=>setModal(true)} className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-red-200 text-sm font-semibold text-red-700"><XCircle size={17}/>Cancel appointment</button>:<p className="mt-6 rounded-xl bg-[#faf8f3] px-4 py-3 text-sm text-[#77776f]">Contact the business to request cancellation{manual?' and refund review':''}.</p>}
    {booking.businessSlug&&<a href={`/${booking.businessSlug}`} className="mt-3 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-[#1d1d1b] text-sm font-semibold text-white">Continue to {booking.businessName}</a>}
  </div></section><ConfirmationDialog open={modal} title="Cancel appointment?" body="Your appointment will be cancelled. Any eligible refund is determined by the policy shown before payment and returned to the original payment method." confirmLabel="Cancel appointment" busy={busy} onCancel={()=>setModal(false)} onConfirm={cancel}/></main>
}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4"><dt className="text-[#77776f]">{label}</dt><dd className="text-right font-medium capitalize">{value}</dd></div>}
function formatTime(value:string){const[h,m]=value.slice(0,5).split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function money(cents:number,currency:string){return new Intl.NumberFormat('en-US',{style:'currency',currency:currency.toUpperCase()}).format(cents/100)}
