'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Calendar, Check, ExternalLink, MessageSquareText, Minus, PackageCheck, Plus, ShieldCheck, ShoppingBag, Ticket, X } from 'lucide-react'
import type { BookingSettings, OrderCustomerSettings, Product, PublicPaymentConfig, RequestServiceSettings, Service } from '@/lib/types'
import { googleCalendarUrl, icsDataUrl, outlookCalendarUrl } from '@/lib/calendar-links'
import { formatDate, formatPhone } from '@/lib/display-format'

const fieldClass='client-commerce-field'
const money=(cents:number,currency='usd')=>new Intl.NumberFormat('en-US',{style:'currency',currency:currency.toUpperCase()}).format(cents/100)

export function OrderModule({businessId,businessName,products,primary,paymentConfig,settings,sectionTitle,preselectedProductId,onClearPreselected}:{businessId:string;businessName:string;products:Product[];primary:boolean;paymentConfig:PublicPaymentConfig;settings:OrderCustomerSettings;sectionTitle?:string;preselectedProductId?:string|null;onClearPreselected?:()=>void}){
  const[quantities,setQuantities]=useState<Record<string,number>>({});const[step,setStep]=useState<'products'|'details'|'review'|'done'>('products');const[details,setDetails]=useState({name:'',phone:'',email:'',method:'pickup',address:'',notes:''});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[confirmed,setConfirmed]=useState<{manageUrl:string;orderReference:string;totalCents:number;paymentRequired:boolean}|null>(null)
  const selected=useMemo(()=>products.filter(p=>quantities[p.id]>0).map(p=>({...p,quantity:quantities[p.id]})),[products,quantities]);const total=selected.reduce((sum,item)=>sum+item.price_cents*item.quantity,0);const online=paymentConfig.order_payment_mode==='online_required'
  const emailRequired=online||settings.email_required;const showEmail=emailRequired||settings.show_email;const showAddress=settings.address_required||settings.show_address||details.method==='delivery';const emailValid=!details.email||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(details.email.trim());const detailsReady=Boolean(details.name.trim()&&(!settings.phone_required||details.phone.trim())&&(!emailRequired||details.email.trim())&&emailValid&&(!settings.address_required||details.address.trim()))
  function quantity(id:string,amount:number){setQuantities(q=>({...q,[id]:Math.max(0,Math.min(99,(q[id]||0)+amount))}))}
  useEffect(()=>{if(!preselectedProductId)return;if(products.some(p=>p.id===preselectedProductId))setQuantities(q=>({...q,[preselectedProductId]:Math.max(1,q[preselectedProductId]||0)}));onClearPreselected?.()},[preselectedProductId,products,onClearPreselected])
  async function submit(){setBusy(true);setError('');try{const response=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({businessId,...details,items:selected.map(p=>({productId:p.id,quantity:p.quantity}))})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to start your order.');setConfirmed({manageUrl:result.manageUrl,orderReference:result.orderReference,totalCents:result.totalCents,paymentRequired:result.paymentRequired});if(result.checkoutUrl){window.location.assign(result.checkoutUrl);return}setStep('done')}catch(e){setError(e instanceof Error?e.message:'Unable to start your order.')}finally{setBusy(false)}}
  return <section id="quicklink-order" className={`client-module client-commerce ${primary?'client-module-primary':''}`}><div className="client-module-heading"><div><span className="client-module-kicker"><ShoppingBag size={13}/>Shop</span><h2>{step==='done'?'Order confirmed':sectionTitle||'Products'}</h2></div><span className="client-step">{step==='products'?'1/3':step==='details'?'2/3':step==='review'?'3/3':''}</span></div>
    {online&&!paymentConfig.payments_ready&&<p className="client-commerce-error">Online ordering is temporarily unavailable while this business finishes payment setup.</p>}
    {step==='products'&&<>{products.length===0?<p className="py-5 text-center text-xs" style={{color:'var(--muted-text)'}}>Products are being added. Please check back soon.</p>:<div className="client-products client-order-cart">{products.map(p=><article key={p.id} className="client-product">{p.image_url?<img src={p.image_url} alt=""/>:<span className="client-service-thumb" aria-hidden="true"/>}<div><strong>{p.name}</strong>{p.description&&<small>{p.description}</small>}<b>{money(p.price_cents,paymentConfig.currency)}</b></div><div className="client-quantity"><button type="button" onClick={()=>quantity(p.id,-1)} aria-label={`Remove ${p.name}`}><Minus size={13}/></button><span>{quantities[p.id]||0}</span><button type="button" onClick={()=>quantity(p.id,1)} aria-label={`Add ${p.name}`}><Plus size={13}/></button></div></article>)}</div>}<button disabled={!selected.length||(online&&!paymentConfig.payments_ready)} className="client-commerce-next" onClick={()=>setStep('details')}>{selected.reduce((s,p)=>s+p.quantity,0)} items · {money(total,paymentConfig.currency)} <ArrowRight size={16}/></button></>}
    {step==='details'&&<div className="client-commerce-form"><input required className={fieldClass} placeholder="Name" value={details.name} onChange={e=>setDetails({...details,name:e.target.value})}/><input required={settings.phone_required} className={fieldClass} type="tel" placeholder={settings.phone_required?'Phone':'Phone (optional)'} value={details.phone} onChange={e=>setDetails({...details,phone:e.target.value})}/>{showEmail&&<input required={emailRequired} className={fieldClass} type="email" placeholder={emailRequired?'Email for your receipt and order updates':'Email (optional)'} value={details.email} onChange={e=>setDetails({...details,email:e.target.value})}/>}<div className="client-choice"><button type="button" className={details.method==='pickup'?'active':''} onClick={()=>setDetails({...details,method:'pickup'})}>Pickup</button><button type="button" className={details.method==='delivery'?'active':''} onClick={()=>setDetails({...details,method:'delivery'})}>Delivery</button></div>{showAddress&&<input required={settings.address_required} className={fieldClass} placeholder={details.method==='delivery'?(settings.address_required?'Delivery address':'Delivery address (optional)'):(settings.address_required?'Pickup customer address':'Address (optional)')} value={details.address} onChange={e=>setDetails({...details,address:e.target.value})}/>} {settings.show_notes&&<textarea className={fieldClass} rows={2} placeholder="Notes (optional)" value={details.notes} onChange={e=>setDetails({...details,notes:e.target.value})}/>} {!emailValid&&<p className="client-commerce-error">Enter a valid email address.</p>}<div className="client-commerce-nav"><button onClick={()=>setStep('products')}><ArrowLeft size={15}/>Back</button><button disabled={!detailsReady} onClick={()=>setStep('review')}>Review order <ArrowRight size={15}/></button></div></div>}
    {step==='review'&&<div className="client-order-review">
      <div className="client-order-summary">
        {selected.map(p=><div key={p.id} className="client-order-summary-row"><span className="client-order-summary-name">{p.name}<small>× {p.quantity}</small></span><strong>{money(p.price_cents*p.quantity,paymentConfig.currency)}</strong></div>)}
        <div className="client-order-summary-total"><span>Order total</span><strong>{money(total,paymentConfig.currency)}</strong></div>
      </div>
      <div className="client-order-delivery">
        <p className="client-order-delivery-title">{details.method==='delivery'?'Delivery':'Pickup'}</p>
        <dl>
          <div><dt>Name</dt><dd>{details.name}</dd></div>
          {details.address.trim()&&<div><dt>Address</dt><dd>{details.address}</dd></div>}
          {details.email.trim()&&<div><dt>Email</dt><dd>{details.email}</dd></div>}
          {details.phone.trim()&&<div><dt>Phone</dt><dd>{formatPhone(details.phone)}</dd></div>}
        </dl>
      </div>
      <div className="client-trust-row"><ShieldCheck size={18}/><div><strong>{online?'Secure payment powered by Stripe':'Payment arranged directly with the business'}</strong><small>{online?'Your order is confirmed after payment succeeds.':'The business will confirm payment details with you.'}</small></div></div>
      {error&&<p className="client-commerce-error">{error}</p>}
      <div className="client-commerce-nav"><button onClick={()=>setStep('details')}><ArrowLeft size={15}/>Back</button><button disabled={busy||!detailsReady} onClick={submit}>{busy?'Preparing…':online?'Continue to payment':'Place order'} <ArrowRight size={15}/></button></div>
    </div>}
    {step==='done'&&confirmed&&<div className="client-commerce-success"><PackageCheck size={28}/><strong>Order confirmed</strong><p>Thank you, {details.name}. {businessName} has your order.</p><div className="client-confirmation-summary"><span>Order #{confirmed.orderReference}</span><strong>{money(confirmed.totalCents,paymentConfig.currency)}</strong></div>{details.email&&<p>A confirmation was sent to {details.email}.</p>}<a className="client-manage-booking" href={confirmed.manageUrl}>View order <ArrowRight size={14}/></a></div>}
  </section>
}

export function RequestServiceModule({businessId,businessName,settings,primary}:{businessId:string;businessName:string;settings:RequestServiceSettings;primary:boolean}){
  const[sent,setSent]=useState<{reference:string;manageUrl:string}|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[name,setName]=useState('');const[email,setEmail]=useState('');const[preferredDate,setPreferredDate]=useState('')
  async function submit(formData:FormData){setBusy(true);setError('');try{const response=await fetch('/api/service-requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({businessId,name:formData.get('name'),phone:formData.get('phone'),email:formData.get('email'),address:formData.get('address'),preferredDate:formData.get('preferredDate'),request:formData.get('request'),notes:formData.get('notes')})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to send request.');setSent({reference:result.reference,manageUrl:result.manageUrl})}catch(e){setError(e instanceof Error?e.message:'Unable to send request.')}finally{setBusy(false)}}
  return <section id="quicklink-request-service" className={`client-module client-commerce ${primary?'client-module-primary':''}`}><div className="client-module-heading"><div><span className="client-module-kicker"><MessageSquareText size={13}/>{settings.title}</span><h2>{settings.description}</h2></div></div>{sent?<div className="client-commerce-success"><Check size={26}/><strong>Request received</strong><p>{businessName} has received your request.</p><div className="client-confirmation-summary"><span>{sent.reference}</span>{preferredDate&&<strong>{formatDate(preferredDate)}</strong>}</div><p>What happens next: the business will review your request and contact you.</p>{email&&<p>We sent a confirmation to {email}.</p>}<a className="client-manage-booking" href={sent.manageUrl}>View request status <ArrowRight size={14}/></a></div>:<form action={submit} className="client-commerce-form"><input required name="name" className={fieldClass} placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input required name="phone" type="tel" className={fieldClass} placeholder="Phone"/>{settings.show_email&&<input required={settings.email_required} name="email" type="email" className={fieldClass} placeholder={settings.email_required?'Email':'Email (recommended)'} value={email} onChange={e=>setEmail(e.target.value)}/>} {settings.show_address&&<input required={settings.address_required} name="address" className={fieldClass} placeholder={settings.address_required?'Address':'Address (optional)'}/>} {settings.show_preferred_date&&<label className="client-date-field"><span>Preferred date</span><input name="preferredDate" type="date" min={new Date().toISOString().slice(0,10)} value={preferredDate} onChange={e=>setPreferredDate(e.target.value)} className={fieldClass}/>{preferredDate&&<small>{formatDate(preferredDate)}</small>}</label>} {settings.show_request&&<textarea required name="request" className={fieldClass} rows={3} placeholder="Tell us what you need"/>} {settings.show_notes&&<textarea name="notes" className={fieldClass} rows={2} placeholder="Extra notes (optional)"/>}{error&&<p className="client-commerce-error">{error}</p>}<button disabled={busy} className="client-commerce-next">{busy?'Sending…':settings.title}<ArrowRight size={16}/></button></form>}</section>
}

export type SelectedBookingOffer={title:string;promoCode?:string;serviceId?:string}
export function BookingModule({businessId,businessName,services,settings,paymentConfig,primary,selectedOffer,selectedServiceId,onClearOffer}:{businessId:string;businessName:string;services:Service[];settings:BookingSettings;paymentConfig:PublicPaymentConfig;primary:boolean;selectedOffer?:SelectedBookingOffer|null;selectedServiceId?:string|null;onClearOffer?:()=>void;onSelectService?:(id:string)=>void;onClearSelectedService?:()=>void}){
  const bookable=useMemo(()=>services.filter(s=>s.enabled&&s.bookable!==false&&(s.action_type||'bookable')==='bookable'),[services]);const initial=selectedOffer?.serviceId||selectedServiceId||bookable.length===1?selectedOffer?.serviceId||selectedServiceId||bookable[0]?.id:'';const[selectedIds,setSelectedIds]=useState<string[]>(initial?[initial]:[]);const[step,setStep]=useState<'service'|'time'|'details'|'done'>(initial?'time':'service');const[date,setDate]=useState(()=>new Date().toISOString().slice(0,10));const[time,setTime]=useState('');const[slots,setSlots]=useState<string[]>([]);const[loadingSlots,setLoadingSlots]=useState(false);const[details,setDetails]=useState({name:'',phone:'',email:'',notes:''});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[confirmed,setConfirmed]=useState<{date:string;time:string;endTime:string;manageUrl:string}|null>(null)
  const selected=bookable.filter(s=>selectedIds.includes(s.id));const total=selected.reduce((sum,s)=>sum+(s.price_cents||0),0);const duration=selected.reduce((sum,s)=>sum+(s.duration_minutes||30),0);const paymentMode=paymentConfig.booking_payment_mode;const due=paymentMode==='full'?total:paymentMode==='deposit'?(paymentConfig.deposit_type==='fixed'?Math.min(total,paymentConfig.deposit_value):Math.min(total,Math.ceil(total*paymentConfig.deposit_value/100))):0;const online=due>0
  useEffect(()=>{const id=selectedOffer?.serviceId||selectedServiceId;if(id&&bookable.some(s=>s.id===id)){setSelectedIds([id]);setStep('time')}},[selectedOffer?.serviceId,selectedServiceId,bookable])
  useEffect(()=>{if(step!=='time'||!selectedIds.length)return;setLoadingSlots(true);setError('');setTime('');const params=new URLSearchParams({businessId,date,serviceIds:selectedIds.join(',')});fetch(`/api/booking/availability?${params}`).then(r=>r.json()).then(result=>{setSlots(result.slots||[]);if(result.error)setError(result.error)}).catch(()=>setError('Unable to load available times.')).finally(()=>setLoadingSlots(false))},[step,date,selectedIds,businessId])
  function toggle(id:string){setSelectedIds(current=>paymentConfig.allow_multiple_services?(current.includes(id)?current.filter(x=>x!==id):[...current,id]):[id])}
  async function submit(){setBusy(true);setError('');try{const response=await fetch('/api/booking',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({businessId,serviceIds:selectedIds,date,time,...details})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to book that time.');if(result.checkoutUrl){window.location.assign(result.checkoutUrl);return}setConfirmed({date,time:result.startTime||time,endTime:result.endTime,manageUrl:result.manageUrl});setStep('done')}catch(e){setError(e instanceof Error?e.message:'Unable to book that time.')}finally{setBusy(false)}}
  const calendarEvent=confirmed?{title:`${selected.map(s=>s.name).join(', ')} — ${businessName}`,description:details.notes||undefined,startISO:`${confirmed.date}T${confirmed.time}:00`,endISO:`${confirmed.date}T${confirmed.endTime}:00`}:null
  return <section id="quicklink-booking" className={`client-module client-commerce ${primary?'client-module-primary':''}`}><div className="client-module-heading"><div><span className="client-module-kicker"><Calendar size={13}/>{settings.button_title||'Book now'}</span><h2>{step==='done'?'Appointment confirmed':step==='service'?'Choose services':step==='time'?'Choose a time':'Your details'}</h2></div></div>
    {selectedOffer&&step!=='done'&&<div className="client-selected-offer"><span className="client-selected-offer-icon"><Ticket size={17}/></span><div><small>Selected offer</small><strong>{selectedOffer.title}</strong>{selectedOffer.promoCode&&<code>{selectedOffer.promoCode}</code>}</div><button type="button" onClick={onClearOffer} aria-label="Remove selected offer"><X size={16}/><span>Clear</span></button></div>}
    {online&&!paymentConfig.payments_ready&&<p className="client-commerce-error">Online booking is temporarily unavailable while this business finishes payment setup.</p>}
    {step==='service'&&<div className="client-commerce-form"><div className="grid gap-2">{bookable.map(s=><button type="button" key={s.id} onClick={()=>toggle(s.id)} className={`client-service client-service-bookable ${selectedIds.includes(s.id)?'ring-2 ring-[#9a6339]':''}`}><span className="client-service-main">{s.image_url&&<img className="client-service-thumb" src={s.image_url} alt=""/>}<span><strong>{s.name}</strong>{s.description&&<small>{s.description}</small>}</span></span><span className="text-right">{s.price_cents!=null&&<strong>{money(s.price_cents,paymentConfig.currency)}</strong>}{s.duration_minutes&&<small>{s.duration_minutes} min</small>}{selectedIds.includes(s.id)?<Check size={15}/>:<Plus size={15}/>}</span></button>)}</div>{selected.length>0&&<div className="rounded-xl bg-[#faf8f3] p-4"><p className="text-xs font-semibold uppercase tracking-[.08em]">Selected services</p>{selected.map(s=><div key={s.id} className="mt-2 flex items-center justify-between gap-3 text-sm"><span>{s.name}</span><button type="button" onClick={()=>toggle(s.id)} aria-label={`Remove ${s.name}`}><X size={15}/></button></div>)}<p className="mt-3 text-xs" style={{color:'var(--muted-text)'}}>Total duration: {duration} min · Total price: {money(total,paymentConfig.currency)}</p></div>}<button disabled={!selectedIds.length||(online&&!paymentConfig.payments_ready)} className="client-commerce-next" onClick={()=>setStep('time')}>Choose a time <ArrowRight size={16}/></button></div>}
    {step==='time'&&<div className="client-commerce-form"><div className="client-selected-service"><div><small>Selected services</small><strong>{selected.map(s=>s.name).join(', ')}</strong><p>{duration} min · {money(total,paymentConfig.currency)}</p></div>{bookable.length>1&&<button type="button" onClick={()=>setStep('service')}>Change</button>}</div><input className={fieldClass} type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)} aria-label="Date"/>{loadingSlots&&<p className="text-xs" style={{color:'var(--muted-text)'}}>Loading available times…</p>}{!loadingSlots&&!error&&!slots.length&&<p className="text-xs" style={{color:'var(--muted-text)'}}>No times available that day. Try another date.</p>}{!loadingSlots&&slots.length>0&&<div className="client-time-grid">{slots.map(slot=><button type="button" key={slot} className={time===slot?'active':''} onClick={()=>setTime(slot)}>{formatTime(slot)}</button>)}</div>}{error&&<p className="client-commerce-error">{error}</p>}<div className="client-commerce-nav"><button type="button" onClick={()=>setStep('service')}><ArrowLeft size={15}/>Back</button><button type="button" disabled={!time} onClick={()=>setStep('details')}>Continue <ArrowRight size={15}/></button></div></div>}
    {step==='details'&&<div className="client-commerce-form"><p className="text-xs" style={{color:'var(--muted-text)'}}>{formatDate(date)} at {formatTime(time)} · {duration} min</p><input className={fieldClass} placeholder="Name" value={details.name} onChange={e=>setDetails({...details,name:e.target.value})}/><input className={fieldClass} type="tel" placeholder="Phone" value={details.phone} onChange={e=>setDetails({...details,phone:e.target.value})}/><input className={fieldClass} type="email" placeholder={online?'Email for your receipt':'Email (recommended)'} value={details.email} onChange={e=>setDetails({...details,email:e.target.value})}/><textarea className={fieldClass} rows={2} placeholder="Notes (optional)" value={details.notes} onChange={e=>setDetails({...details,notes:e.target.value})}/><div className="rounded-xl border p-4 text-sm"><p className="flex justify-between"><span>Service total</span><strong>{money(total,paymentConfig.currency)}</strong></p>{paymentMode==='deposit'&&<><p className="mt-2 flex justify-between"><span>Deposit due today</span><strong>{money(due,paymentConfig.currency)}</strong></p><p className="mt-2 flex justify-between text-xs" style={{color:'var(--muted-text)'}}><span>Remaining at appointment</span><strong>{money(total-due,paymentConfig.currency)}</strong></p></>}{paymentMode==='full'&&<p className="mt-2 text-xs" style={{color:'var(--muted-text)'}}>Full payment is due securely through Stripe.</p>}{paymentMode==='none'&&<p className="mt-2 text-xs" style={{color:'var(--muted-text)'}}>No online payment is required.</p>}<p className="mt-3 border-t pt-3 text-xs" style={{color:'var(--muted-text)'}}>{paymentConfig.booking_refund_policy==='window'?`Refundable until ${paymentConfig.cancellation_window_hours} hours before the appointment.`:paymentConfig.booking_refund_policy==='non_refundable'?'Payments are non-refundable.':'Cancellations and refunds require business approval.'}</p></div>{error&&<p className="client-commerce-error">{error}</p>}<div className="client-commerce-nav"><button type="button" onClick={()=>setStep('time')}><ArrowLeft size={15}/>Back</button><button type="button" disabled={busy||!details.name||!details.phone||(online&&!details.email)} onClick={submit}>{busy?'Preparing…':online?'Continue to payment':'Confirm booking'} <ArrowRight size={15}/></button></div></div>}
    {step==='done'&&confirmed&&<div className="client-commerce-success"><PackageCheck size={28}/><strong>You're booked, {details.name}.</strong><p>{formatDate(confirmed.date)} at {formatTime(confirmed.time)} · {selected.map(s=>s.name).join(', ')}</p>{calendarEvent&&<div className="client-add-to-calendar"><a href={googleCalendarUrl(calendarEvent)} target="_blank" rel="noreferrer">Google Calendar <ExternalLink size={13}/></a><a href={outlookCalendarUrl(calendarEvent)} target="_blank" rel="noreferrer">Outlook <ExternalLink size={13}/></a><a href={icsDataUrl(calendarEvent)} download="appointment.ics">Apple / other (.ics)</a></div>}<a className="client-manage-booking" href={confirmed.manageUrl}>Manage appointment <ArrowRight size={14}/></a></div>}
  </section>
}

function formatTime(value:string){const[h,m]=value.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
