'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { CheckCircle2, ExternalLink, PackageCheck, XCircle } from 'lucide-react'
import { formatDateTime, formatPhone } from '@/lib/display-format'
import { orderReference } from '@/lib/order-manage-client'
import StatusTimeline from '@/components/status-timeline'
import ConfirmationDialog from '@/components/confirmation-dialog'

type ManagedOrder = { id:string;customer_name:string;customer_phone:string;customer_email:string|null;fulfillment_method:string;address:string|null;notes:string|null;total_cents:number;status:string;payment_status:string;currency:string;policy_snapshot:Record<string,unknown>;amount_paid_cents:number;amount_refunded_cents:number;receipt_url:string|null;created_at:string;business_name:string;business_slug:string;business_email:string|null;items:Array<{product_name:string;unit_price_cents:number;quantity:number}> }

export default function OrderManageCard({token,order}:{token:string;order:ManagedOrder}) {
  const router=useRouter()
  const [status,setStatus]=useState(order.status);const[paymentStatus,setPaymentStatus]=useState(order.payment_status);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[modal,setModal]=useState(false)
  const policy=String(order.policy_snapshot?.order_cancellation_policy||'new_only')
  const cancellable=status==='pending_payment'||status==='new'||(status==='confirmed'&&policy==='new_confirmed')
  const refundCents=Math.max(0,order.amount_paid_cents-order.amount_refunded_cents)
  useEffect(()=>{setStatus(order.status);setPaymentStatus(order.payment_status)},[order.status,order.payment_status])
  useEffect(()=>{if(status!=='pending_payment'&&paymentStatus!=='pending')return;let tries=0;const timer=window.setInterval(()=>{tries+=1;router.refresh();if(tries>=15)window.clearInterval(timer)},2000);return()=>window.clearInterval(timer)},[status,paymentStatus,router])
  async function cancel(){setBusy(true);setError('');const response=await fetch('/api/orders/manage/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,confirm:'CANCEL'})});const result=await response.json();setBusy(false);if(!response.ok){setError(result.error||'Unable to cancel this order.');setModal(false)}else{setStatus('cancelled');if(result.refund)setPaymentStatus(result.refund.status==='succeeded'?'refunded':'refund_pending');setModal(false)}}
  const paymentLabel=paymentStatus==='not_required'?'Pay at pickup/delivery':paymentStatus.replaceAll('_',' ')
  return <main className="min-h-screen bg-[#f6f3ed] px-4 py-10 text-[#1d1d1b]"><section className="mx-auto max-w-2xl overflow-hidden rounded-3xl border border-[#ded8cc] bg-white shadow-[0_24px_70px_rgba(38,28,17,.12)]"><div className="border-b border-[#e8e2d8] bg-[#1d1d1b] px-6 py-7 text-white"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#d19a6a]">Quicklink order</p><h1 className="mt-2 text-2xl font-semibold">Order #{orderReference(order.id)}</h1><p className="mt-1 text-sm text-white/60">{order.business_name}</p></div><div className="p-6 sm:p-8">
    {status==='pending_payment'&&<p className="mb-5 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">Payment is pending. Your order becomes active only after Stripe confirms payment.</p>}
    {paymentStatus==='paid'&&<div className="mb-5 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-emerald-900"><p className="flex items-center gap-2 font-semibold"><CheckCircle2 size={18}/>Order confirmed</p><p className="mt-1 text-sm">Paid {money(order.amount_paid_cents,order.currency)}{order.customer_email?` · A receipt was sent to ${order.customer_email}.`:'.'}</p></div>}
    <div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#f2e8db] text-[#9a6339]"><PackageCheck size={22}/></span><div><h2 className="text-xl font-semibold">{status==='cancelled'?'Order cancelled':'Thank you, '+order.customer_name+'.'}</h2><p className="mt-1 text-sm text-[#77776f]">Created {formatDateTime(order.created_at)}</p></div></div>
    <StatusTimeline status={status} steps={status==='pending_payment'?[{value:'pending_payment',label:'Payment pending'}]:[{value:'new',label:'Received'},{value:'confirmed',label:'Confirmed'},{value:'preparing',label:'Preparing'},{value:'ready',label:'Ready'},{value:'completed',label:'Completed'}]}/>
    <div className="mt-7 grid gap-5 md:grid-cols-2"><section className="rounded-2xl bg-[#faf8f3] p-5"><h3 className="text-xs font-semibold uppercase tracking-[.1em] text-[#77776f]">Customer &amp; fulfillment</h3><dl className="mt-3 grid gap-2 text-sm"><Row label="Customer" value={order.customer_name}/><Row label="Phone" value={formatPhone(order.customer_phone)}/><Row label="Method" value={order.fulfillment_method==='delivery'?'Delivery':'Pickup'}/>{order.address&&<Row label="Address" value={order.address}/>} {order.notes&&<Row label="Notes" value={order.notes}/>}</dl></section><section className="rounded-2xl bg-[#faf8f3] p-5"><h3 className="text-xs font-semibold uppercase tracking-[.1em] text-[#77776f]">Status</h3><dl className="mt-3 grid gap-2 text-sm"><Row label="Order" value={status.replaceAll('_',' ')}/><Row label="Payment" value={paymentLabel}/><Row label="Paid" value={money(order.amount_paid_cents,order.currency)}/>{order.amount_refunded_cents>0&&<Row label="Refunded" value={money(order.amount_refunded_cents,order.currency)}/>}</dl>{order.receipt_url&&<a href={order.receipt_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-[#8b6b3d]">View payment receipt <ExternalLink size={13}/></a>}</section></div>
    <section className="mt-5"><h3 className="text-xs font-semibold uppercase tracking-[.1em] text-[#77776f]">Order summary</h3><div className="mt-3 divide-y rounded-2xl border border-[#e8e2d8] px-4">{order.items.map((item,index)=><div key={`${item.product_name}-${index}`} className="flex justify-between gap-3 py-3 text-sm"><span>{item.quantity}× {item.product_name}</span><strong>{money(item.unit_price_cents*item.quantity,order.currency)}</strong></div>)}<div className="flex justify-between py-4"><strong>Total</strong><strong>{money(order.total_cents,order.currency)}</strong></div></div></section>
    {error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    {status==='cancelled'?<div className="mt-6 flex items-center gap-2 rounded-xl bg-[#faf8f3] px-4 py-3 text-sm font-medium"><CheckCircle2 size={18} className="text-[#9a6339]"/>This order has been cancelled{paymentStatus==='refund_pending'?' and the refund is processing.':paymentStatus==='refunded'?' and refunded.':'.'}</div>:cancellable?<button type="button" onClick={()=>setModal(true)} className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-red-200 text-sm font-semibold text-red-700"><XCircle size={17}/>Cancel order</button>:<p className="mt-6 rounded-xl bg-[#faf8f3] px-4 py-3 text-sm text-[#77776f]">Contact the business to request cancellation.</p>}<a href={`/${order.business_slug}`} className="mt-3 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-[#1d1d1b] text-sm font-semibold text-white">Continue to {order.business_name}</a>
  </div></section>
  <ConfirmationDialog open={modal} title="Cancel order?" body={`Order #${orderReference(order.id)} will be cancelled.${refundCents > 0 ? ` ${money(refundCents, order.currency)} will be refunded to the original payment method.` : ''}`} confirmLabel={refundCents > 0 ? 'Cancel & refund' : 'Cancel order'} busy={busy} onCancel={()=>setModal(false)} onConfirm={cancel}/>
  </main>
}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4"><dt className="text-[#77776f]">{label}</dt><dd className="text-right font-medium capitalize">{value}</dd></div>}
function money(cents:number,currency:string){return new Intl.NumberFormat('en-US',{style:'currency',currency:currency.toUpperCase()}).format(cents/100)}
